test.cs
Forgot to add void. Still cannot run: encountering <error CS2012: Cannot open 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\test.exe' for writing -- 'Access to the path 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\test.exe' is denied.'>